/**
 * BulletinBoard Client SDK
 *
 * Midnight Compact TypeScript adapter for bulletin-board.compact.
 */

import {
  type CircuitContext,
  type QueryContext,
  type WitnessContext,
  type ConstructorContext,
  type ConstructorResult,
  type CircuitResults,
  type StateValue,
  type ChargedState,
} from '@midnight-ntwrk/compact-runtime';

import {
  Contract as ManagedContract,
  ledger,
  type Witnesses as ContractWitnesses,
  type Ledger as ContractLedger,
} from '../../contracts/managed/bulletin-board/contract/index.js';

/**
 * Off-chain private state schema required by the Bulletin Board witness runtime.
 */
export interface BulletinBoardPrivateState {
  readonly secretKey: Uint8Array;
}

/**
 * Strongly typed ledger state representation generated by Compact compiler.
 */
export type BulletinBoardLedgerState = ContractLedger;

/**
 * Strongly typed witness interface matching Bulletin Board contract requirements.
 * Witness methods return a tuple [nextPrivateState, witnessReturnValue].
 */
export interface BulletinBoardWitnesses<PS = BulletinBoardPrivateState> {
  localSecretKey: (context: WitnessContext<ContractLedger, PS>) => [PS, Uint8Array];
}

/**
 * Creates default witnesses that extract the secretKey from BulletinBoardPrivateState.
 */
export function createDefaultWitnesses<PS extends BulletinBoardPrivateState>(): BulletinBoardWitnesses<PS> {
  return {
    localSecretKey: (context: WitnessContext<ContractLedger, PS>): [PS, Uint8Array] => {
      const { privateState } = context;
      if (!privateState?.secretKey) {
        throw new Error('BulletinBoardWitnesses: Missing secretKey in private state');
      }
      if (privateState.secretKey.length !== 32) {
        throw new Error(
          `BulletinBoardWitnesses: secretKey must be 32 bytes, received ${privateState.secretKey.length} bytes`
        );
      }
      return [privateState, privateState.secretKey];
    },
  };
}

/**
 * Production-grade client SDK for interacting with the Midnight Bulletin Board contract.
 */
export class BulletinBoardClient<PS = BulletinBoardPrivateState> {
  private readonly contract: ManagedContract<PS>;

  /**
   * Initializes a new BulletinBoardClient instance.
   *
   * @param witnesses Optional custom witness implementations. Defaults to standard witness resolvers.
   */
  constructor(witnesses?: BulletinBoardWitnesses<PS>) {
    const activeWitnesses = witnesses ?? (createDefaultWitnesses() as unknown as BulletinBoardWitnesses<PS>);
    this.contract = new ManagedContract<PS>(activeWitnesses as unknown as ContractWitnesses<PS>);
  }

  /**
   * Generates the initial contract and private state for deployment.
   *
   * @param context Constructor context with private state and coin public key.
   * @returns ConstructorResult containing the initial contract state and private state.
   */
  public initialState(context: ConstructorContext<PS>): ConstructorResult<PS> {
    return this.contract.initialState(context);
  }

  /**
   * Posts a new message if the board is VACANT, or updates an existing post if caller is owner.
   *
   * @param context Circuit context containing contract address, keys, state, and private state.
   * @param newMessage The text message to post.
   * @returns CircuitResults containing the execution context and unit tuple result `[]`.
   */
  public postMessage(context: CircuitContext<PS>, newMessage: string): CircuitResults<PS, []> {
    return this.contract.circuits.postMessage(context, newMessage);
  }

  /**
   * Takes down an existing post on an OCCUPIED board. Caller must be the current owner.
   *
   * @param context Circuit context containing contract address, keys, state, and private state.
   * @returns CircuitResults containing the execution context and the removed message string.
   */
  public takeDown(context: CircuitContext<PS>): CircuitResults<PS, string> {
    return this.contract.circuits.takeDown(context);
  }

  /**
   * Decodes and reads the public ledger state from raw or charged contract state.
   *
   * @param rawState Raw ledger state value from query context or charged state.
   * @returns Decoded strongly-typed BulletinBoardLedgerState.
   */
  public queryLedgerState(rawState: StateValue | ChargedState | unknown): BulletinBoardLedgerState {
    return ledger(rawState as StateValue | ChargedState);
  }

  public queryLedgerStateFromRaw(rawState: StateValue | ChargedState | unknown): BulletinBoardLedgerState {
    return ledger(rawState as StateValue | ChargedState);
  }
}